const atoms={hydrogen:{name:'Hydrogen',symbol:'H',displaySymbol:'H₂',type:'Khí nhẹ',number:'01',color:'#bfe3cf'},helium:{name:'Helium',symbol:'He',displaySymbol:'He',type:'Khí hiếm',number:'02',color:'#e9d8f0'},lithium:{name:'Lithium',symbol:'Li',displaySymbol:'Li',type:'Kim loại kiềm',number:'03',color:'#f0c4c1'},beryllium:{name:'Beryllium',symbol:'Be',displaySymbol:'Be',type:'Kim loại kiềm thổ',number:'04',color:'#d8e1bc'},boron:{name:'Boron',symbol:'B',displaySymbol:'B',type:'Á kim',number:'05',color:'#d8c9a9'},carbon:{name:'Carbon',symbol:'C',displaySymbol:'C',type:'Phi kim',number:'06',color:'#ddd4c4'},nitrogen:{name:'Nitrogen',symbol:'N',displaySymbol:'N₂',type:'Khí trơ',number:'07',color:'#c6d8ef'},oxygen:{name:'Oxygen',symbol:'O',displaySymbol:'O₂',type:'Khí hoạt tính',number:'08',color:'#b8dce5'},fluorine:{name:'Fluorine',symbol:'F',displaySymbol:'F₂',type:'Halogen',number:'09',color:'#d8edb8'},neon:{name:'Neon',symbol:'Ne',displaySymbol:'Ne',type:'Khí hiếm',number:'10',color:'#f3c2bd'},sodium:{name:'Sodium',symbol:'Na',displaySymbol:'Na',type:'Kim loại kiềm',number:'11',color:'#f0ce87'},magnesium:{name:'Magnesium',symbol:'Mg',displaySymbol:'Mg',type:'Kim loại kiềm thổ',number:'12',color:'#d9e5bc'},aluminum:{name:'Aluminum',symbol:'Al',displaySymbol:'Al',type:'Kim loại',number:'13',color:'#d9dfe5'},silicon:{name:'Silicon',symbol:'Si',displaySymbol:'Si',type:'Á kim',number:'14',color:'#d9d0c1'},phosphorus:{name:'Phosphorus',symbol:'P',displaySymbol:'P',type:'Phi kim',number:'15',color:'#f2d0a4'},sulfur:{name:'Sulfur',symbol:'S',displaySymbol:'S',type:'Phi kim',number:'16',color:'#f2e092'}};
const compounds={'hydrogen+oxygen':{id:'water',name:'Water',symbol:'H₂O',formula:'2H₂ + O₂ → 2H₂O',color:'#9ed9df',xp:120},'carbon+oxygen':{id:'co2',name:'Carbon Dioxide',symbol:'CO₂',formula:'C + O₂ → CO₂',color:'#c9d7c7',xp:140},'hydrogen+carbon':{id:'methane',name:'Methane',symbol:'CH₄',formula:'C + 2H₂ → CH₄',color:'#d9c7e5',xp:150},'hydrogen+sodium':{id:'sodiumHydride',name:'Sodium Hydride',symbol:'NaH',formula:'2Na + H₂ → 2NaH',color:'#edd39a',xp:180},'oxygen+sodium':{id:'sodiumOxide',name:'Sodium Oxide',symbol:'Na₂O',formula:'4Na + O₂ → 2Na₂O',color:'#edb978',xp:160},'carbon+sodium':{id:'sodiumCarbide',name:'Sodium Carbide',symbol:'Na₂C₂',formula:'2Na + 2C → Na₂C₂',color:'#e9c7ac',xp:200}};
const valences={hydrogen:1,helium:0,lithium:1,beryllium:2,boron:3,carbon:4,nitrogen:3,oxygen:2,fluorine:1,neon:0,sodium:1,magnesium:2,aluminum:3,silicon:4,phosphorus:3,sulfur:2};const subscriptNumber=value=>value===1?'':String(value).replace(/[0-9]/g,d=>'₀₁₂₃₄₅₆₇₈₉'[d]);const gcd=(a,b)=>b?gcd(b,a%b):a;function generatedFormula(firstId,secondId,first,second){const firstValence=valences[firstId]||1;const secondValence=valences[secondId]||1;if(!firstValence||!secondValence)return `${first.symbol}${second.symbol}`;const divisor=gcd(firstValence,secondValence);return `${first.symbol}${subscriptNumber(secondValence/divisor)}${second.symbol}${subscriptNumber(firstValence/divisor)}`;}
const baseElementEntries=Object.entries(atoms);baseElementEntries.forEach(([firstId,first],firstIndex)=>baseElementEntries.slice(firstIndex+1).forEach(([secondId,second])=>{const key=[firstId,secondId].sort().join('+');if(compounds[key])return;const metals=['Kim loại kiềm','Kim loại kiềm thổ','Kim loại'];const bond=metals.includes(first.type)&&metals.includes(second.type)?'Liên kết kim loại':metals.includes(first.type)||metals.includes(second.type)?'Liên kết ion':first.type==='Khí hiếm'||second.type==='Khí hiếm'?'Lực Van der Waals':'Liên kết cộng hóa trị';const formula=generatedFormula(firstId,secondId,first,second);compounds[key]={id:`compound-${firstId}-${secondId}`,name:`${first.name} ${second.name}`,symbol:formula,displaySymbol:formula,formula:`${first.symbol} + ${second.symbol} → ${formula}`,color:first.color,xp:80+((firstIndex+secondId.length)%5)*20,bond,note:`${bond} hình thành khi ${first.name} kết hợp với ${second.name}.`};}));
Object.assign(compounds,{'hydrogen+oxygen':{bond:'Liên kết cộng hóa trị'},'carbon+oxygen':{bond:'Liên kết cộng hóa trị'},'hydrogen+carbon':{bond:'Liên kết cộng hóa trị'},'hydrogen+sodium':{bond:'Liên kết ion'},'oxygen+sodium':{bond:'Liên kết ion'},'carbon+sodium':{bond:'Liên kết kim loại'}});
const baseAtomIds=new Set(Object.keys(atoms));const maxDiscoveries=Object.keys(atoms).length*(Object.keys(atoms).length-1)/2;const state={xp:+localStorage.getItem('hoa-xp')||0,found:JSON.parse(localStorage.getItem('hoa-found')||'[]'),selected:[],wrongCount:0};const $=s=>document.querySelector(s);const list=$('#elementList');
const clickSound=new Audio('sound/click.mp3');clickSound.preload='auto';clickSound.volume=.4;
const successSound=new Audio('sound/dung.mp3');successSound.preload='auto';successSound.volume=.7;
const failSound=new Audio('sound/sai.mp3');failSound.preload='auto';failSound.volume=.8;
const angrySound=new Audio('sound/youstupdnigg.mp3');angrySound.preload='auto';angrySound.volume=.9;
const bookSound=new Audio('sound/sotay.mp3');bookSound.preload='auto';bookSound.volume=.7;
function playClickSound(){try{if(!clickSound)return;clickSound.volume=.4;clickSound.currentTime=0;clickSound.play().catch(()=>{});}catch(e){}}
function playSuccessSound(){try{if(!successSound)return;successSound.volume=.7;successSound.currentTime=0;successSound.play().catch(()=>{});}catch(e){}}
function playFailSound(){try{if(!failSound)return;failSound.volume=.8;failSound.currentTime=0;failSound.play().catch(()=>{});}catch(e){}}
function playAngrySound(){try{if(!angrySound)return;angrySound.volume=.9;angrySound.currentTime=0;angrySound.play().catch(()=>{});}catch(e){}}
function playBookSound(){try{if(!bookSound)return;bookSound.volume=.7;bookSound.currentTime=0;bookSound.play().catch(()=>{});}catch(e){}}
function normalizeCompound(product){if(!product)return null;product.displaySymbol=product.displaySymbol||product.symbol;product.symbol=product.symbol||product.displaySymbol;product.formula=product.formula||product.symbol;product.bond=product.bond||'Liên kết cộng hóa trị';product.color=product.color||'#bfe3cf';return product;}
function triggerMascotAngry(){const mascot=$('#panelMascot');if(!mascot)return;mascot.src='img/unaangry.png';mascot.style.width='230px';mascot.style.transform='scale(1.08)';mascot.style.filter='drop-shadow(0 10px 20px rgba(0,0,0,.28))';clearTimeout(triggerMascotAngry.timer);triggerMascotAngry.timer=setTimeout(()=>{mascot.src='img/unanabeo.png';mascot.style.width='140px';mascot.style.transform='scale(1)';mascot.style.filter='drop-shadow(0 6px 14px rgba(0,0,0,.25))';},500);}
function findCompound(id){const product=Object.values(compounds).find(item=>item.id===id);return product?normalizeCompound(product):null;}
function registerCompound(product){product=normalizeCompound(product);if(atoms[product.id])return;atoms[product.id]={name:product.name,symbol:product.symbol,displaySymbol:product.displaySymbol,type:'Hợp chất mới',number:String(Object.keys(atoms).length+1).padStart(2,'0'),color:product.color};}
function restoreCompounds(){state.found.forEach(id=>{const product=findCompound(id);if(product)registerCompound(product);});}
function renderAtoms(){const query=($('#elementSearch')?.value||'').trim().toLowerCase();const visibleAtoms=Object.entries(atoms).filter(([,a])=>`${a.name} ${a.symbol} ${a.type}`.toLowerCase().includes(query)).sort(([,first],[,second])=>Number(first.number)-Number(second.number));$('#elementCount').textContent=String(Object.keys(atoms).length).padStart(2,'0');list.innerHTML=visibleAtoms.map(([id,a])=>`<button class="element" draggable="true" data-id="${id}" type="button" style="--element-color:${a.color}"><span class="element-symbol" style="background:${a.color}">${a.displaySymbol||a.symbol}</span><span class="element-name">${a.name}<small>${a.type}</small></span><span class="element-number">Z${a.number}</span></button>`).join('')||'<p class="no-results">Không tìm thấy nguyên tố.</p>';list.querySelectorAll('.element').forEach(button=>{button.onclick=()=>{playClickSound();select(button.dataset.id);};button.ondragstart=e=>{playClickSound();e.dataTransfer.setData('text/plain',button.dataset.id);};});}
function renderSelected(){const selected=$('#selectedAtoms');selected.innerHTML=state.selected.map(id=>`<span class="selected-atom" style="--atom-color:${atoms[id].color}"><b>${atoms[id].displaySymbol||atoms[id].symbol}</b><small>${atoms[id].name}</small></span>`).join('');$('#reactionZone').classList.toggle('has-selection',state.selected.length>0);}
function select(id){state.selected.push(id);renderSelected();if(state.selected.length===1){showToast(`${atoms[id].name} đã vào vùng ghép. Chọn thêm một nguyên tố.`);return;}combine(...state.selected);}
function combine(a,b){const product=normalizeCompound(compounds[[a,b].sort().join('+')]);if(!product){state.selected=[];renderSelected();state.wrongCount=(state.wrongCount||0)+1;playFailSound();triggerMascotAngry();if(state.wrongCount>=3){playAngrySound();showToast('Sai quá 3 lần! Cẩn thận hơn nhé!');}else{showToast('Hai nguyên tố này chưa có trong công thức hiện tại.');}$('#result').innerHTML='<span class="result-icon">!</span><p>Chưa tìm thấy phản ứng. Hãy thử một cặp khác.</p>';return;}state.wrongCount=0;const fresh=!state.found.includes(product.id);if(fresh)state.found.push(product.id);registerCompound(product);state.selected=[];renderSelected();state.xp+=product.xp;localStorage.setItem('hoa-xp',state.xp);localStorage.setItem('hoa-found',JSON.stringify(state.found));playSuccessSound();$('#result').innerHTML=`<span class="result-icon">✦</span><p><b>${fresh?'Phát hiện mới: ':''}${product.name}</b> · ${product.formula} <span class="bond-badge">${product.bond}</span> <strong>+${product.xp} XP</strong></p>`;renderAtoms();render();showToast(`${product.name} · ${product.bond}`);}
function render(){('#xp');$('#xp').textContent=String(state.xp).padStart(3,'0');$('#discovered').textContent=`${Math.min(state.found.length,maxDiscoveries)}/${maxDiscoveries}`;$('#discoveryList').innerHTML=state.found.length?state.found.slice(-3).reverse().map(findCompound).filter(Boolean).map(p=>`<div class="discovery"><span class="discovery-icon" style="background:${p.color}">${p.displaySymbol||p.symbol}</span><div><strong>${p.name}</strong><small>${p.formula}</small><em class="bond-label">${p.bond}</em></div></div>`).join(''):'<span class="empty">Chưa có nguyên tố mới. Hãy bắt đầu khám phá.</span>';}
function renderBook(){const query=($('#bookSearch')?.value||'').trim().toLowerCase();const matches=state.found.map(findCompound).filter(Boolean).filter(p=>`${p.name} ${p.displaySymbol||p.symbol} ${p.formula}`.toLowerCase().includes(query));$('#bookList').innerHTML=matches.length?matches.map(p=>`<div class="book-entry"><span class="discovery-icon" style="background:${p.color}">${p.displaySymbol||p.symbol}</span><div><strong>${p.name}</strong><p>${p.formula}</p><em class="bond-label">${p.bond}</em></div></div>`).join(''):state.found.length?'<p class="book-no-results">Không tìm thấy trong sổ tay.</p>':'<p>Những trang đầu tiên vẫn còn trống.</p>';}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2300);}const showToast=toast;const zone=$('#reactionZone');zone.ondragover=e=>{e.preventDefault();zone.classList.add('over')};zone.ondragleave=()=>zone.classList.remove('over');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('over');playClickSound();select(e.dataTransfer.getData('text/plain'))};zone.onclick=()=>showToast('Hãy chọn hai nguyên tố ở bảng bên phải.');$('#reset').onclick=()=>{if(confirm('Xóa toàn bộ tiến trình?')){state.xp=0;state.found=[];Object.keys(atoms).forEach(id=>{if(!baseAtomIds.has(id))delete atoms[id];});localStorage.removeItem('hoa-xp');localStorage.removeItem('hoa-found');renderAtoms();render();renderBook();showToast('Đã đặt lại phòng thí nghiệm.')}};
$('#openBook').onclick=()=>{playBookSound();renderBook();$('#bookModal').classList.add('open')};$('#closeBook').onclick=()=>$('#bookModal').classList.remove('open');$('.backdrop').onclick=()=>$('#bookModal').classList.remove('open');$('#elementSearch').addEventListener('input',renderAtoms);$('#bookSearch').addEventListener('input',renderBook);restoreCompounds();renderAtoms();render();
